version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.dockerfile
        ports:
            -   8098:80
        volumes:
            - ./:/var/www/laravel-docker
        links:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.dockerfile
        volumes:
            -   ./:/var/www/laravel-docker
            - type: "bind"
              source: "/tmp"
              target: "/tmp"
        links:
            -   mysql
    mysql:
        platform: linux/x86_64 # add for mac m1
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
        -   3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: "Europe/Kiev"
            #MYSQL_DATABASE: laravel
        volumes:
            - mysql-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql

volumes:
    mysql-data:
